// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qGh94E7rNZSsJTjhMsRo4F
// Component: 2jeeYfeGWiP97
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_minimalist_about_me_page.module.css"; // plasmic-import: qGh94E7rNZSsJTjhMsRo4F/projectcss
import * as sty from "./PlasmicSocialIcon.module.css"; // plasmic-import: 2jeeYfeGWiP97/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: SfY2eyHZAdE05/icon

export type PlasmicSocialIcon__VariantMembers = {};

export type PlasmicSocialIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicSocialIcon__VariantsArgs;
export const PlasmicSocialIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicSocialIcon__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicSocialIcon__ArgsType;
export const PlasmicSocialIcon__ArgProps = new Array<ArgPropType>("children");

export type PlasmicSocialIcon__OverridesType = {
  root?: p.Flex<"a">;
};

export interface DefaultSocialIconProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicSocialIcon__RenderFunc(props: {
  variants: PlasmicSocialIcon__VariantsArgs;
  args: PlasmicSocialIcon__ArgsType;
  overrides: PlasmicSocialIcon__OverridesType;
  dataFetches?: PlasmicSocialIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <a
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      href={"/" as const}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <IconIcon
            className={classNames(defaultcss.all, sty.svg__juIEl)}
            role={"img"}
          />
        ),

        value: args.children
      })}
    </a>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSocialIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSocialIcon__VariantsArgs;
    args?: PlasmicSocialIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSocialIcon__Fetches;
  } & Omit<PlasmicSocialIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSocialIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSocialIcon__ArgProps,
      internalVariantPropNames: PlasmicSocialIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSocialIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSocialIcon";
  } else {
    func.displayName = `PlasmicSocialIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicSocialIcon = Object.assign(
  // Top-level PlasmicSocialIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSocialIcon
    internalVariantProps: PlasmicSocialIcon__VariantProps,
    internalArgProps: PlasmicSocialIcon__ArgProps
  }
);

export default PlasmicSocialIcon;
/* prettier-ignore-end */
